Controllers/NavbarController.cs
using Microsoft.AspNetCore.Mvc;

namespace QuanLyThuoc.Controllers
{
    public class NavbarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult PrivacyPolicy()
        {
            return View();
        }

        public IActionResult TermsOfUse()
        {
            return View();
        }

        public IActionResult SalesAndRefunds()
        {
            return View();
        }
    }
}

Controllers/ThuocController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyThuoc.Data;
using QuanLyThuoc.ViewModel;

namespace QuanLyThuoc.Controllers
{
    public class ThuocController : Controller
    {
        private readonly QuanlythuocContext db;

        public ThuocController(QuanlythuocContext context)
        {
            db = context;
        }
        public IActionResult Index(int? DanhMuc)
        {
            var thuocs = db.Thuocs.AsQueryable();

            if (DanhMuc != null)
            {
                thuocs = thuocs.Where(p => p.MaDanhMuc == DanhMuc);
            }

            var result = thuocs.Select(p => new ThuocVM
            {
                MaThuoc = p.MaThuoc,
                TenThuoc = p.TenThuoc ?? "",
                GiaBan = p.GiaBan,
                HinhAnh = p.HinhAnh ?? "",
                MoTaNgan = p.MoTaNgan ?? "",
                TenLoai = p.MaDanhMucNavigation.TenDanhMuc ?? ""
            });

            return View(result);
        }

        public IActionResult Search(string? query)
        {
            var thuocs = db.Thuocs.AsQueryable();

            if (query != null)
            {
                thuocs = thuocs.Where(p => p.TenThuoc.Contains(query));
            }

            var result = thuocs.Select(p => new ThuocVM
            {
                MaThuoc = p.MaThuoc,
                TenThuoc = p.TenThuoc ?? "",
                GiaBan = p.GiaBan,
                HinhAnh = p.HinhAnh ?? "",
                MoTaNgan = p.MoTaNgan ?? "",
                TenLoai = p.MaDanhMucNavigation.TenDanhMuc
            });

            return View(result);
        }

        public IActionResult Detail(int id)
        {
            var data = db.Thuocs
                .Include(p => p.MaDanhMucNavigation)
                .SingleOrDefault(p => p.MaThuoc == id);
            if (data == null)
            {
                TempData["Message"] = $"Không tìm thấy sản phẩm có mã {id}";
                return Redirect("/404");
            }

            var result = new ChiTietThuocVM
            {
                MaThuoc = data.MaThuoc,
                TenThuoc = data.TenThuoc ?? "",
                GiaBan = data.GiaBan,
                ChiTietThuoc = data.ChiTietThuoc ?? "",
                HinhAnh = data.HinhAnh ?? "",
                MoTaNgan = data.MoTaNgan ?? "",
                TenLoai = data.MaDanhMucNavigation.TenDanhMuc,
                SoLuongTon = 10,
                DiemDanhGia = 5,
			};
            return View(result);
        }
    }
}

ViewComponents/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyThuoc.Helper;
using QuanLyThuoc.ViewModel;

namespace QuanLyThuoc.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var cart = HttpContext.Session.Get<List<CartItem>>
                    (MySetting.CART_KEY) ?? new List<CartItem>();

            var model = new CartModel
            {
                Quanlity = cart.Sum(p => p.SoLuong),
                Total = cart.Sum(p => p.ThanhTien)
            };

            return View("CartPanel", model);
        }
    }
}

Views/Shared/_DanhSachThuoc.cshtml
@{
    ViewData["Title"] = "DanhSachThuoc";
    Layout = "_LayoutCustomer";
}


<!-- Single Page Header start -->
@RenderSection("BreadCum", required: false)
<!-- Single Page Header End -->
<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <h1 class="mb-4">Nhà Thuốc Á Châu</h1>
        <div class="row g-4">
            <div class="col-lg-12">
                <div class="row g-4">
                    <div class="col-xl-3">
                        <div class="input-group w-100 mx-auto d-flex">
                            @await Html.PartialAsync("_TimKiemPanel")
                        </div>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-xl-3">
                        
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-lg-3">
                        <div class="row g-4 mt-3">
                            @await Component.InvokeAsync("MenuDanhMuc")
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="row g-4 justify-content-center">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- Fruits Shop End-->

Views/Shared/_Footer.cshtml
@{
    ViewData["Title"] = "_Footer";
}

<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item d-flex flex-column">
                    <h4 class="text-light mb-3">Về Pharmacity</h4>
                    <a class="btn-link" href="">Giới Thiệu</a>
                    <a class="btn-link" href="">Quy chế hoạt động</a>
                    <a class="btn-link" href="">Chính sách giao hàng</a>
                    <a class="btn-link" href="">Chính sách bảo mật</a>
                    <a class="btn-link" href="">Chính sách Thanh Toán</a>                    
                    <a class="btn-link" href="">Hệ Thống cửa hàng</a>
                    <a class="btn-link" href="">Câu hỏi thường gặp</a>
                    <a class="btn-link" href="">Bảo vệ dữ liệu cá nhân</a>
                    <a class="btn-link" href="">Site map</a>
                    <a class="btn-link" href="">Bệnh viện</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Những dịch vụ hiện có</h4>
                    <a class="btn-link" href="">Hỗ trợ đặt hàng</a>
                    <a class="btn-link" href="">Thông tin nhà thuốc</a>
                    <a class="btn-link" href="">Thiếu nại, Góp ý</a>
                    <a class="btn-link" href="">Hỗ trợ khách hàng</a>
                    <a class="btn-link" href="">Tư vấn Thuốc</a>
                    <a class="btn-link" href="">Chăm sóc định kỳ</a>
                    <a class="btn-link" href="">Lịch hẹn khám</a>
                    <a class="btn-link" href="">Khám chuyên sâu</a>
                    <a class="btn-link" href="">Tình trạng khẩn cấp</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Theo Dõi Chúng Tôi Trên</h4>
                    <div class="d-flex flex-row text-start footer-item gap-5">
                        <div>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                            <p class="mt-2">Twitter</p>
                        </div>
                        <div>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                            <p class="mt-2">facebook</p>
                        </div>
                        <div>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                            <p class="mt-2">youtube</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row text-start footer-item gap-3">
                    <img src="~/Hinh/Dow/dmca.png" alt="Alternate Text" style="height: 40px;" />
                    <img src="~/Hinh/Dow/bocongthuong.png" alt="Alternate Text" style="height: 40px;" />
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Tải xuống ứng dụng</h4>
                    <div>
                        <a href="#"><img src="~/Hinh/Dow/20240706154633-0-app-store.png" style="height: 40px;" /></a>
                    </div>
                    <div>
                        <a href="#"><img src="~/Hinh/Dow/20240706154633-0-google-play.png" style="height: 40px; margin-top: 10px;" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->
<!-- Copyright Start -->
<div class="container-fluid copyright bg-dark py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                <span class="text-light">
                    <a href="#">
                        <i class="fas fa-copyright text-light me-2"></i>Công Ty Cổ Phần Dược Phẩm Pharmacity
                        Trụ sở: 248A Nơ Trang Long, P.12, Q.Bình Thạnh, TP.Hồ Chí Minh
                        Điện thoại: 1800 6821 - Email: cskh@pharmacity.vn
                    </a>
                </span>
            </div>
            <div class="col-md-6 my-auto text-center text-md-end text-white">
                GCNDKDN: 0311770883 do sở KH & ĐT TP.HCM cấp lần đầu ngày 05/05/2012.
                GCNDDKKDD: 6782/DDKKDDD-ĐNai ngày cấp 26/4/2022 Sở Y Tế Tỉnh Đồng Nai.
            </div>
        </div>
    </div>
</div>
<!-- Copyright End -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuanLyThuoc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuanLyThuoc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuanLyThuoc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - QuanLyThuoc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    @RenderSection("Styles", required: false);
</head>
<body>
    <div>
        <!-- Spinner Start -->
        <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar start -->
        <div class="container-fluid fixed-top">
            <div class="container topbar bg-primary d-none d-lg-block">
                <div class="d-flex justify-content-between">
                    <div class="top-info ps-2">
                        <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">248A Nơ Trang Long, P.12, Q.Bình Thạnh, HCM</a></small>
                        <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">cskh@pharmacity.vn</a></small>
                    </div>
                    <div class="top-link pe-2">
                        <a asp-action="PrivacyPolicy" asp-controller="Navbar" class="text-white"><small class="text-white mx-2">Chính sách bảo mật</small>/</a>
                        <a asp-action="SalesAndRefunds" asp-controller="Navbar" class="text-white"><small class="text-white mx-2">Bán hàng và Sử Dụng</small>/</a>
                        <a asp-action="TermsOfUse" asp-controller="Navbar" class="text-white"><small class="text-white ms-2">Các điều khoản</small></a>
                    </div>
                </div>
            </div>
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a asp-action="Index" asp-controller="Home" class="navbar-brand"><h1 class="text-primary display-6">PRAMACY</h1></a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a asp-action="Index" asp-controller="Home" class="nav-item nav-link active">Home</a>
                            <a asp-controller="Thuoc" asp-action="Index" class="nav-item nav-link">Shop</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Member</a>
                                <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a asp-controller="KhachHang" asp-action="Profile" class="dropdown-item">Profile</a>
                                        <a asp-controller="KhachHang" asp-action="DangXuat" class="dropdown-item">Logout</a>
                                    }
                                    else
                                    {
                                        <a asp-controller="KhachHang" asp-action="DangKy" class="dropdown-item">Đăng ký</a>
                                        <a asp-controller="KhachHang" asp-action="DangNhap" class="dropdown-item">Đăng nhập</a>
                                    }
                                </div>
                            </div>
                            <a  class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="d-flex m-3 me-0">
                            <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>
                            
                            @await Component.InvokeAsync("Cart")

                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="KhachHang" asp-action="Profile" title="Xem thông tin người dùng" class="my-auto">
                                    <i class="fas fa-user fa-2x"></i>
                                </a>
                            }
                            else
                            {
                                <a asp-controller="KhachHang" asp-action="DangNhap" title="Đăng nhập nha" class="my-auto">
                                    <i class="fas fa-user fa-2x"></i>
                                </a>
                            }


                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->
        <!-- Modal Search Start -->
        <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <div class="input-group w-75 mx-auto d-flex">
                            <input id="SearchText" type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                            <span id="SearchButton" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Search End -->

        
            @RenderBody()
        

        @await Html.PartialAsync("_Footer")
    </div>

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false);

    <script>
        $(document).ready(function () {
            $("#SearchButton").click(function () {
                let url = `/Thuoc/Search?query=` + $("#SearchText").val();
                window.location.href = url;
            });
        });
    </script>
</body>
</html>

Views/Shared/_TimKiemPanel.cshtml
<form name="SearchForm" asp-action="Search" asp-controller="Thuoc">
	<div class="input-group w-100 mx-auto d-flex">
		<input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="searchButton" name="query" id="searchText">
		<span id="searchButton" class="input-group-text p-3" onclick="SearchForm.submit()"><i class="fa fa-search"></i></span>
	</div>
</form>